version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install boto3
  build:
    commands:
      - chmod +x crear_registros.sh
      - ./crear_registros.sh
      - python validar_registros.py
  post_build:
    commands:
      - echo "Desplegando página web a S3..."
      # Reemplaza 'nombre-de-tu-bucket-web' por el bucket donde quieres ver la página
      - aws s3 cp index.html s3://act.20.04/index.html
      - echo "Despliegue finalizado exitosamente."
