version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install boto3
  build:
    commands:
      - chmod +x crear_registros.sh
      - ./crear_registros.sh
      - python validar_registros.py
  post_build:
    commands:
      - echo "Desplegando página web a S3..."
      - aws s3 cp index.html s3://mi-pagina2/index.html
